#!/usr/bin/env python3
"""Generate the bundle manifest — the single source of truth for "what must be inside the build".

Walks the repository and records:
  * every ``jarvis.*`` module in ``src/`` (so PyInstaller gets a --hidden-import for each one)
  * every top-level script / data file that the app needs at runtime (app.py, prompts.py, ...)
  * every payload tree that ships as real source code inside the installer

Outputs:
  * ``src/jarvis/_manifest.py``            — imported at runtime by ``jarvis selftest``
  * ``deploy/windows/hiddenimports.txt``   — one module per line, consumed by CI / build_msi.ps1
  * ``deploy/windows/pyinstaller_args.txt``— ready-made ``--hidden-import`` argument string

Usage:
    python deploy/gen_manifest.py            # write files
    python deploy/gen_manifest.py --check    # fail (exit 1) if files are stale  [used in CI]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
PKG = SRC / "jarvis"

# Top-level python files that ship next to the package (bundled as data + payload).
ROOT_SCRIPTS = ["app.py", "client.py", "prompts.py"]

# Directory trees copied verbatim into the install folder (the "complete code" payload).
PAYLOAD_TREES = [
    "src",
    "configs",
    "docs",
    "examples",
    "assets",
    "frontend/src",
    "deploy/windows",
    "deploy/linux",
    "tests",
    # The holographic web interface (React + Three.js) and its Node bridge.
    "web",
]

#: Directory names never shipped: build output, dependencies, vendored WASM.
EXCLUDE_DIRS = {"node_modules", "dist", "dist-ssr", "build", ".git", "mediapipe", "__pycache__"}

# Single files copied into the install folder alongside the payload trees.
PAYLOAD_FILES = [
    "app.py",
    "client.py",
    "prompts.py",
    "pyproject.toml",
    "README.md",
    "INSTALL.md",
    "Makefile",
    "frontend/package.json",
    "frontend/index.html",
    "frontend/vite.config.ts",
    "setup_business_os.bat",
    "setup_business_os.sh",
]

# Third-party imports that PyInstaller regularly misses (optional at runtime).
OPTIONAL_THIRD_PARTY = [
    "faiss",
    "sentence_transformers",
    "numpy",
    "tavily",
    "ddgs",
    "rank_bm25",
    "litellm",
    "ollama",
    "fastapi",
    "uvicorn",
    "tomlkit",
    "httpx",
    "pydantic",
    "click",
    "rich",
    "tkinter",
]

HEADER = '''"""AUTO-GENERATED by ``python deploy/gen_manifest.py`` — do not edit by hand.

This manifest is what ``jarvis selftest`` checks against, so a build that is missing
modules (the classic "the MSI doesn't contain the complete code" failure) fails loudly
instead of silently degrading to a stub UI.
"""

'''


def discover_modules() -> list[str]:
    """Every importable ``jarvis.*`` module under src/."""
    mods: set[str] = set()
    for path in sorted(PKG.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        rel = path.relative_to(SRC)
        parts = list(rel.with_suffix("").parts)
        if parts[-1] == "__init__":
            parts = parts[:-1]
        if not parts:
            continue
        mods.add(".".join(parts))
    return sorted(mods)


def discover_payload_files() -> list[str]:
    """Flat list of repo-relative files that must exist inside the installed payload."""
    files: set[str] = set()
    for name in PAYLOAD_FILES:
        if (ROOT / name).is_file():
            files.add(name)
    for tree in PAYLOAD_TREES:
        base = ROOT / tree
        if not base.is_dir():
            continue
        for path in base.rglob("*"):
            if not path.is_file():
                continue
            if EXCLUDE_DIRS.intersection(path.parts) or path.suffix in {".pyc", ".pyo"}:
                continue
            files.add(path.relative_to(ROOT).as_posix())
    return sorted(files)


def read_version() -> str:
    init = PKG / "__init__.py"
    for line in init.read_text(encoding="utf-8").splitlines():
        if line.startswith("__version__"):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return "0.0.0"


def render_manifest(version: str, modules: list[str], payload: list[str]) -> str:
    out = [HEADER]
    out.append(f'VERSION = "{version}"\n\n')
    out.append("#: Every jarvis.* module that must be importable in a complete build.\n")
    out.append("MODULES = [\n")
    out.extend(f'    "{m}",\n' for m in modules)
    out.append("]\n\n")
    out.append("#: Top-level scripts bundled as data next to the package.\n")
    out.append("ROOT_SCRIPTS = [\n")
    out.extend(f'    "{s}",\n' for s in ROOT_SCRIPTS)
    out.append("]\n\n")
    out.append("#: Optional third-party packages — reported but never fatal.\n")
    out.append("OPTIONAL_THIRD_PARTY = [\n")
    out.extend(f'    "{m}",\n' for m in OPTIONAL_THIRD_PARTY)
    out.append("]\n\n")
    out.append("#: Source files shipped verbatim in the installer payload (repo-relative).\n")
    out.append("PAYLOAD_FILES = [\n")
    out.extend(f'    "{f}",\n' for f in payload)
    out.append("]\n\n")
    out.append("MODULE_COUNT = len(MODULES)\n")
    out.append("PAYLOAD_FILE_COUNT = len(PAYLOAD_FILES)\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if generated files are stale")
    args = ap.parse_args()

    version = read_version()
    modules = discover_modules()
    payload = discover_payload_files()

    manifest_py = PKG / "_manifest.py"
    hidden_txt = ROOT / "deploy" / "windows" / "hiddenimports.txt"
    args_txt = ROOT / "deploy" / "windows" / "pyinstaller_args.txt"

    manifest_content = render_manifest(version, modules, payload)
    hidden_content = "\n".join(modules + OPTIONAL_THIRD_PARTY) + "\n"
    args_content = " ".join(f"--hidden-import {m}" for m in modules + OPTIONAL_THIRD_PARTY) + "\n"

    targets = {
        manifest_py: manifest_content,
        hidden_txt: hidden_content,
        args_txt: args_content,
    }

    if args.check:
        stale = [p for p, c in targets.items() if not p.exists() or p.read_text(encoding="utf-8") != c]
        if stale:
            print("Manifest is STALE — run: python deploy/gen_manifest.py", file=sys.stderr)
            for p in stale:
                print(f"  - {p.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"Manifest up to date: {len(modules)} modules, {len(payload)} payload files")
        return 0

    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    print(f"v{version}: {len(modules)} jarvis modules, {len(payload)} payload files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
