"""Autostart manager — make JARVIS start when machine starts.

Supports:
- Windows: Startup folder + Task Scheduler + Registry
- Linux: systemd user service + autostart .desktop
- macOS: LaunchAgent plist

Usage:
  from jarvis.startup.autostart import get_autostart_manager
  mgr = get_autostart_manager()
  mgr.enable()  # Enable autostart
  mgr.disable() # Disable
  mgr.status()  # Check status
"""

from __future__ import annotations

import os
import sys
import platform
import pathlib
import subprocess
import json
from typing import Dict, Any


class AutostartManager:
    def __init__(self):
        self.system = platform.system()
        self.home = pathlib.Path.home()

    def status(self) -> Dict[str, Any]:
        """Check autostart status."""
        if self.system == "Windows":
            return self._status_windows()
        elif self.system == "Linux":
            return self._status_linux()
        elif self.system == "Darwin":
            return self._status_macos()
        else:
            return {"enabled": False, "system": self.system, "message": f"Unsupported OS: {self.system}"}

    def enable(self, mode: str = "gui") -> Dict[str, Any]:
        """
        Enable autostart.
        mode: gui (desktop GUI), cli (CLI chat), server (web server), ironman (Iron Man HUD)
        """
        if self.system == "Windows":
            return self._enable_windows(mode)
        elif self.system == "Linux":
            return self._enable_linux(mode)
        elif self.system == "Darwin":
            return self._enable_macos(mode)
        else:
            return {"success": False, "message": f"Unsupported OS: {self.system}"}

    def disable(self) -> Dict[str, Any]:
        if self.system == "Windows":
            return self._disable_windows()
        elif self.system == "Linux":
            return self._disable_linux()
        elif self.system == "Darwin":
            return self._disable_macos()
        else:
            return {"success": False, "message": f"Unsupported OS: {self.system}"}

    # Windows
    def _status_windows(self) -> Dict[str, Any]:
        startup_folder = self.home / "AppData" / "Roaming" / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"
        jarvis_bat = startup_folder / "JARVIS.bat"
        jarvis_lnk = startup_folder / "JARVIS.lnk"
        
        enabled = jarvis_bat.exists() or jarvis_lnk.exists()
        
        # Check registry
        try:
            import winreg
            key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\Microsoft\Windows\CurrentVersion\Run", 0, winreg.KEY_READ)
            try:
                winreg.QueryValueEx(key, "JARVIS")
                enabled = True
            except FileNotFoundError:
                pass
            winreg.CloseKey(key)
        except:
            pass

        return {
            "enabled": enabled,
            "system": "Windows",
            "startup_folder": str(startup_folder),
            "bat_exists": jarvis_bat.exists(),
            "message": "Enabled" if enabled else "Disabled — run enable() to add to startup"
        }

    def _enable_windows(self, mode: str = "gui") -> Dict[str, Any]:
        startup_folder = self.home / "AppData" / "Roaming" / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"
        startup_folder.mkdir(parents=True, exist_ok=True)

        # Create batch file that starts JARVIS
        bat_path = startup_folder / "JARVIS.bat"
        
        # Find jarvis executable or python
        jarvis_cmd = self._find_jarvis_cmd(mode)
        
        bat_content = f"""@echo off
REM JARVIS Autostart — Good morning!
REM Mode: {mode}
REM Generated by JARVIS autostart manager

echo Starting JARVIS {mode} mode...
cd /d "%USERPROFILE%"

REM Try to start JARVIS
{jarvis_cmd}

REM If failed, try python -m jarvis
if %errorlevel% neq 0 (
  python -m jarvis.cli.main {mode} 2>nul || python -m jarvis {mode} 2>nul || echo JARVIS not found in PATH
)

REM Keep window open for 2 sec then minimize
timeout /t 2 >nul
"""
        
        try:
            bat_path.write_text(bat_content, encoding="utf-8")
            
            # Also try registry for more reliable autostart
            try:
                import winreg
                key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\Microsoft\Windows\CurrentVersion\Run", 0, winreg.KEY_SET_VALUE)
                winreg.SetValueEx(key, "JARVIS", 0, winreg.REG_SZ, f'"{bat_path}"')
                winreg.CloseKey(key)
            except Exception as e:
                print(f"Registry autostart failed (non-critical): {e}")

            return {
                "success": True,
                "message": f"JARVIS autostart enabled for {mode} mode. Will start on boot.",
                "path": str(bat_path),
                "mode": mode,
                "instructions": "Reboot to test, or check Task Manager > Startup"
            }
        except Exception as e:
            return {"success": False, "message": f"Failed to enable autostart: {e}"}

    def _disable_windows(self) -> Dict[str, Any]:
        startup_folder = self.home / "AppData" / "Roaming" / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"
        bat_path = startup_folder / "JARVIS.bat"
        lnk_path = startup_folder / "JARVIS.lnk"

        removed = []
        for p in [bat_path, lnk_path]:
            if p.exists():
                try:
                    p.unlink()
                    removed.append(str(p))
                except Exception as e:
                    return {"success": False, "message": f"Failed to remove {p}: {e}"}

        # Remove registry
        try:
            import winreg
            key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\Microsoft\Windows\CurrentVersion\Run", 0, winreg.KEY_SET_VALUE)
            try:
                winreg.DeleteValue(key, "JARVIS")
                removed.append("Registry HKCU\\...\\Run\\JARVIS")
            except FileNotFoundError:
                pass
            winreg.CloseKey(key)
        except:
            pass

        return {
            "success": True,
            "message": f"JARVIS autostart disabled. Removed: {', '.join(removed) if removed else 'nothing found'}",
            "removed": removed
        }

    # Linux
    def _status_linux(self) -> Dict[str, Any]:
        autostart_dir = self.home / ".config" / "autostart"
        desktop_file = autostart_dir / "jarvis.desktop"
        
        systemd_user = self.home / ".config" / "systemd" / "user" / "jarvis.service"
        
        enabled = desktop_file.exists() or systemd_user.exists()
        
        return {
            "enabled": enabled,
            "system": "Linux",
            "desktop_file": str(desktop_file),
            "systemd_service": str(systemd_user),
            "message": "Enabled" if enabled else "Disabled"
        }

    def _enable_linux(self, mode: str = "gui") -> Dict[str, Any]:
        autostart_dir = self.home / ".config" / "autostart"
        autostart_dir.mkdir(parents=True, exist_ok=True)

        jarvis_cmd = self._find_jarvis_cmd(mode)
        
        desktop_content = f"""[Desktop Entry]
Type=Application
Name=JARVIS
Comment=Personal AI — Good morning!
Exec={jarvis_cmd}
Icon=utilities-terminal
Terminal=false
Categories=Utility;
X-GNOME-Autostart-enabled=true
"""
        
        desktop_file = autostart_dir / "jarvis.desktop"
        try:
            desktop_file.write_text(desktop_content)

            # Also systemd user service for server mode
            if mode in ("server", "ironman", "adhd"):
                systemd_dir = self.home / ".config" / "systemd" / "user"
                systemd_dir.mkdir(parents=True, exist_ok=True)
                service_file = systemd_dir / "jarvis.service"
                service_content = f"""[Unit]
Description=JARVIS Personal AI — {mode}
After=graphical-session.target

[Service]
Type=simple
ExecStart={jarvis_cmd}
Restart=on-failure
Environment=PATH={os.environ.get('PATH','')}
Environment=HOME={self.home}

[Install]
WantedBy=default.target
"""
                service_file.write_text(service_content)
                # Enable
                try:
                    subprocess.run(["systemctl", "--user", "enable", "jarvis.service"], capture_output=True)
                    subprocess.run(["systemctl", "--user", "daemon-reload"], capture_output=True)
                except:
                    pass

            return {
                "success": True,
                "message": f"JARVIS autostart enabled ({mode}). Desktop file: {desktop_file}",
                "path": str(desktop_file),
                "mode": mode
            }
        except Exception as e:
            return {"success": False, "message": f"Failed: {e}"}

    def _disable_linux(self) -> Dict[str, Any]:
        autostart_dir = self.home / ".config" / "autostart"
        desktop_file = autostart_dir / "jarvis.desktop"
        systemd_file = self.home / ".config" / "systemd" / "user" / "jarvis.service"

        removed = []
        for f in [desktop_file, systemd_file]:
            if f.exists():
                try:
                    f.unlink()
                    removed.append(str(f))
                except Exception as e:
                    return {"success": False, "message": f"Failed to remove {f}: {e}"}

        try:
            subprocess.run(["systemctl", "--user", "disable", "jarvis.service"], capture_output=True)
        except:
            pass

        return {"success": True, "message": f"Disabled. Removed: {', '.join(removed) if removed else 'none'}", "removed": removed}

    # macOS
    def _status_macos(self) -> Dict[str, Any]:
        plist_path = self.home / "Library" / "LaunchAgents" / "com.jarvis.autostart.plist"
        return {
            "enabled": plist_path.exists(),
            "system": "Darwin",
            "plist": str(plist_path),
            "message": "Enabled" if plist_path.exists() else "Disabled"
        }

    def _enable_macos(self, mode: str = "gui") -> Dict[str, Any]:
        launch_agents = self.home / "Library" / "LaunchAgents"
        launch_agents.mkdir(parents=True, exist_ok=True)
        plist_path = launch_agents / "com.jarvis.autostart.plist"

        jarvis_cmd = self._find_jarvis_cmd(mode)
        # Split cmd for plist
        cmd_parts = jarvis_cmd.split()

        plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.jarvis.autostart</string>
    <key>ProgramArguments</key>
    <array>
        {"".join(f"<string>{p}</string>" for p in cmd_parts)}
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>{self.home}/.jarvis/jarvis-autostart.log</string>
    <key>StandardErrorPath</key>
    <string>{self.home}/.jarvis/jarvis-autostart.log</string>
</dict>
</plist>
"""
        try:
            plist_path.write_text(plist_content)
            subprocess.run(["launchctl", "load", str(plist_path)], capture_output=True)
            return {"success": True, "message": f"Autostart enabled ({mode}). Plist: {plist_path}", "path": str(plist_path), "mode": mode}
        except Exception as e:
            return {"success": False, "message": f"Failed: {e}"}

    def _disable_macos(self) -> Dict[str, Any]:
        plist_path = self.home / "Library" / "LaunchAgents" / "com.jarvis.autostart.plist"
        try:
            if plist_path.exists():
                subprocess.run(["launchctl", "unload", str(plist_path)], capture_output=True)
                plist_path.unlink()
                return {"success": True, "message": f"Disabled, removed {plist_path}", "removed": [str(plist_path)]}
            return {"success": True, "message": "Already disabled", "removed": []}
        except Exception as e:
            return {"success": False, "message": f"Failed: {e}"}

    def _find_jarvis_cmd(self, mode: str) -> str:
        """Find best command to start JARVIS in given mode."""
        # Check if jarvis in PATH
        import shutil
        jarvis_bin = shutil.which("jarvis")
        
        if mode == "gui":
            # Try jarvis-desktop, then gui, then python app.py
            desktop_bin = shutil.which("jarvis-desktop")
            if desktop_bin:
                return desktop_bin
            if jarvis_bin:
                return f"{jarvis_bin} ironman --engine mock"
            return f"{sys.executable} -m jarvis.cli.main ironman --engine mock"
        elif mode == "ironman":
            if jarvis_bin:
                return f"{jarvis_bin} ironman --engine mock"
            return f"{sys.executable} -m jarvis.cli.main ironman --engine mock"
        elif mode == "adhd":
            if jarvis_bin:
                return f"{jarvis_bin} adhd --engine mock"
            return f"{sys.executable} -m jarvis.cli.main adhd --engine mock"
        elif mode == "server":
            if jarvis_bin:
                return f"{jarvis_bin} serve"
            return f"{sys.executable} -m jarvis.server.api"
        else:
            if jarvis_bin:
                return jarvis_bin
            return f"{sys.executable} -m jarvis.cli.main"


def get_autostart_manager() -> AutostartManager:
    return AutostartManager()


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="JARVIS Autostart Manager")
    parser.add_argument("--enable", action="store_true", help="Enable autostart")
    parser.add_argument("--disable", action="store_true", help="Disable autostart")
    parser.add_argument("--status", action="store_true", help="Check status")
    parser.add_argument("--mode", default="gui", help="Mode: gui, ironman, adhd, server, cli")
    args = parser.parse_args()

    mgr = get_autostart_manager()
    if args.enable:
        print(json.dumps(mgr.enable(args.mode), indent=2))
    elif args.disable:
        print(json.dumps(mgr.disable(), indent=2))
    elif args.status:
        print(json.dumps(mgr.status(), indent=2))
    else:
        parser.print_help()
